version: "3.8"

services:
  go-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-test
    restart: always
    ports:
      - "5001:5000"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
